## Common elasticsearch configuration parameters ##

elasticsearch_cluster_name: development-cluster

# Minimum master nodes in cluster, 2 for 3 nodes elasticsearch cluster
minimum_master_nodes: 2

# Java memory heap values for elasticsearch
xms_value: 2
xmx_value: 2

# Elasticsearch version
es_version: "7.1.1"
es_major_version: "7.x"

# Configure hostnames for Elasticsearch nodes
# Example es1.example.com, es2.example.com
domain_name: example.com

# Kibana version
kibana_version: "7.1.1"
kibana_major_version: "7.x"
