---
# Variables for Opendistro security plugin installation

# Install opendistro plugin
opendistro_security_install: true

# opendistro plugin version
opendistro_security_version: 1.1.0.0

# URL to download the opendistro plugins
opendistro_security_download_url: https://d3g5vo6xdbdb9a.cloudfront.net/downloads/elasticsearch-plugins/opendistro-security/

## Admin user credentials will be used for User & Roles management and cluster operations
admin_password: Test@7890

## Kibana server credentials will be used internally by the Kibana server
kibanaserver_password: Test@6789
